package enchantment.domain.errors

class AlreadyEnchantedError : Exception()